CREATE OR REPLACE PROCEDURE return_npedidos(nomeCliente IN CLIENTE.NOME_CLI%type)
RETURN INTEGER
IS 
totalPedidos INTEGER;
Mauro INTEGER;
BEGIN
	SELECT SUM(A.QUANTIDADE) INTO Mauro
	FROM ITEM_DO_PEDIDO A RIGHT JOIN
	PEDIDO B ON (A.COD_PED = B.COD_PED)
	RIGHT JOIN CLIENTE
	ON (CLIENTE.COD_CLI = B.COD_CLI)
	WHERE (CLIENTE.NOME_CLI = nomeCliente);
	RETURN Mauro;
END return_npedidos;

SELECT return_npedidos(‘Mauro’)
FROM DUAL;
